Drop Table if exists [DB].[Schema].Justin_Locks_Piovt_Loop
select FacilityID,  Analysis, Type, [53], [BELLEVILLE LOCKS & DAM], [CANNELTON LOCK & DAM], [CAPT ANT MELDAHL LOCK & DAM]
,[CHAINS OF ROCKS L/D 27],[DRESDEN ISLAND LOCK & DAM],[GREENUP LOCKS & DAM], [HANNIBAL LOCKS & DAM],
[JOHN T. MYERSLOCK & DAM], [LAGRANGE LOCK & DAM], [LOCK & DAM 10], [LOCK & DAM 11],
[LOCK & DAM 12], [LOCK & DAM 13],[LOCK & DAM 14], [LOCK & DAM 15], [LOCK & DAM 16],
[LOCK & DAM 17],[LOCK & DAM 18], [LOCK & DAM 19], [LOCK & DAM 2], [LOCK & DAM 20], [LOCK & DAM 21], [LOCK & DAM 22], [lOCK & DAM 24],[LOCK & DAM 25],
[LOCK & DAM 3], [LOCK & DAM 4], [LOCK & DAM 5], [LOCK & DAM 52], [LOCK & DAM 5A], [LOCK & DAM 6], [LOCK & DAM 7], [LOCK & DAM 8], [LOCK & DAM 9],
[MARKLAND LOCKS & DAM], [MARSEILLES LOCK & DAM], [MCALPINE LOCKS & DAM], [MEL PRICE LOCK & DAM], [NEW CUMBERLAND LOCK & DAM],
[NEWBURGH LOCK & DAM], [OLMSTED LOCKS AND DAM], [PEORIA LOCK & DAM], [PIKE ISLAND LOCK & DAM], [RACINE LOCKS & DAM], [ROBERT C. BYRD],
[SMITHLAND LOCK & DAM],[STARVED ROCK LOCK & DAM],[WILLOW ISLAND LOCKS & DAM] into [DB].[Schema].Justin_Locks_Piovt_Loop
from (select  FacilityID as FacilityID, Analysis, Type, PMSNAME as PMSNAME from [DB].[Schema].Justin_LoopLocks) as datasource 
PIVOT(count(PMSNAME) for PMSNAME IN([53], [BELLEVILLE LOCKS & DAM], [CANNELTON LOCK & DAM], [CAPT ANT MELDAHL LOCK & DAM]
,[CHAINS OF ROCKS L/D 27],[DRESDEN ISLAND LOCK & DAM],[GREENUP LOCKS & DAM], [HANNIBAL LOCKS & DAM],
[JOHN T. MYERSLOCK & DAM], [LAGRANGE LOCK & DAM], [LOCK & DAM 10], [LOCK & DAM 11],
[LOCK & DAM 12], [LOCK & DAM 13],[LOCK & DAM 14], [LOCK & DAM 15], [LOCK & DAM 16],
[LOCK & DAM 17],[LOCK & DAM 18], [LOCK & DAM 19], [LOCK & DAM 2], [LOCK & DAM 20], [LOCK & DAM 21], [LOCK & DAM 22], [lOCK & DAM 24],[LOCK & DAM 25],
[LOCK & DAM 3], [LOCK & DAM 4], [LOCK & DAM 5], [LOCK & DAM 52], [LOCK & DAM 5A], [LOCK & DAM 6], [LOCK & DAM 7], [LOCK & DAM 8], [LOCK & DAM 9],
[MARKLAND LOCKS & DAM], [MARSEILLES LOCK & DAM], [MCALPINE LOCKS & DAM], [MEL PRICE LOCK & DAM], [NEW CUMBERLAND LOCK & DAM],
[NEWBURGH LOCK & DAM], [OLMSTED LOCKS AND DAM], [PEORIA LOCK & DAM], [PIKE ISLAND LOCK & DAM], [RACINE LOCKS & DAM], [ROBERT C. BYRD],
[SMITHLAND LOCK & DAM],[STARVED ROCK LOCK & DAM],[WILLOW ISLAND LOCKS & DAM])) as pivottable


